In [1]:
import numpy as np

np.__version__

'1.19.5'

作業目標<br>
活用矩陣運算，實做線性代數<br>
作業重點<br>
線性代數公式應用<br>
矩陣相乘維度需要對好，例如:2X3矩陣乘上3X5矩陣得到2X5矩陣

題目:<br>
array1 = np.array([[10, 8], [3, 5]]) <br>
1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
2. 運用上列array計算特徵值、特徵向量?
3. 運用上列array計算SVD?

In [20]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])

(m,n) = np.shape(array1)
if m == n:
    inv_a1 = np.linalg.inv(array1)
    print("the Inverse of array1 is:\n", inv_a1)
else:
    print((m,n), ", not a square matrix!")


print('----------')

if False not in (np.dot(array1, inv_a1) == np.identity(n)):
    print('array1 x array1_I = \n', np.dot(array1, inv_a1), '\tis a identity matrix.')
else:
    print('array1 x array1_I is not a identity matrix.')
    

the Inverse of array1 is:
 [[ 0.19230769 -0.30769231]
 [-0.11538462  0.38461538]]
----------
array1 x array1_I = 
 [[1. 0.]
 [0. 1.]] 	is a identity matrix.


In [21]:
#2. 運用上列array計算特徵值、特徵向量?
(t, v) = np.linalg.eig(array1)

print("the eigenvalue is:\n", t)
print("\nthe eigenvector is:\n", v)

the eigenvalue is:
 [13.  2.]

the eigenvector is:
 [[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [38]:
#3. 運用上列array計算SVD?
(U, sig, Vh) = np.linalg.svd(array1)

print("the result of singular value decomposition on array1 is :\nU:\n", U, '\n\tsig:\n\t', sig, '\nVh:\n', Vh)

the result of singular value decomposition on array1 is :
U:
 [[-0.91663818 -0.39971796]
 [-0.39971796  0.91663818]] 
	sig:
	 [13.94721714  1.86417116] 
Vh:
 [[-0.74319741 -0.6690722 ]
 [-0.6690722   0.74319741]]
