作業目標<br>
熟悉陣列維度轉換，並且會擷取需要資料<br>
作業重點<br>
使用reshap須注意order用法<br>
where可以運用邏輯條件擷取資料

題目:<br>
1.將下列陣列(array1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")<br>
2.呈上題的array，找出被6除餘1的數的索引<br>

In [56]:
import numpy as np
np.__version__

'1.19.5'

In [87]:
#1.將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
array1 = np.array(range(30))
print('array1: --> ', array1, '\n')
a11 = array1.reshape((5, -1), order = 'F')
print("Answer 1-1 :\n", a11, '\n')

#print(array1, '\n')

a13 = np.resize(array1, (6, 5)).transpose()
print("Answer 1-2 :\n", a13, '\n')

print('array1: --> ', array1, '\n')


# 若array直接進行resize,會無法print且會改變原array??
# a12 = array1.resize((5, 6), refcheck = False)
# print(a12, '\n')

# print(array1, '\n')


array1: -->  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] 

Answer 1-1 :
 [[ 0  5 10 15 20 25]
 [ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]] 

Answer 1-2 :
 [[ 0  5 10 15 20 25]
 [ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]] 

array1: -->  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] 



In [88]:
#2.呈上題的array，找出被6除餘1的數的索引
array1 = np.array(range(30))
print(array1, '\n ============= \n')

a21 = np.where((array1 % 6) == 1)
print("Answer 2-1 :\n", a21, '\n ------------ \n')

a22 = (array1 % 6).argsort(kind='mergesort')[5:10]
print("Answer 2-2 :\n", a22, '\n')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] 

Answer 2-1 :
 (array([ 1,  7, 13, 19, 25], dtype=int64),) 
 ------------ 

Answer 2-2 :
 [ 1  7 13 19 25] 

